#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later

# Copyright 2020 Benjamin Gordon.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Takes one or more log files generated by the inside monitoring scripts
# and plots speed and SNR over time.  You will need:
#   * gnuplot 5 or later for the chart
#   * mlr (http://johnkerl.org/miller/doc/index.html) to preprocess the log

outfile="$1"
if [[ -z "$outfile" ]]; then
    echo "Usage: $0 outfile.png infile [infile2 ...]"
    exit 1
fi
shift

datafile=$(mktemp)

mlr --t2c cut -f "Check Timestamp,External IP,Dn Kbps,Up Kbps,SNR Dn,SNR Up" \
    "then" sort -f "Check Timestamp" \
    "then" put 'if (${External IP} == "0.0.0.0") { ${External IP} = "1" } else { ${External IP} = "0" }' \
    "then" rename "External IP,Outage" \
    "$@" > "$datafile"

startdate="$(head -n2 "$datafile" | cut -f1 -d, | tail -n1 | sed -e 's/T.*/T00:00:00/')"
enddate="$(date -d "$(tail -n1 "$datafile" | cut -f1 -d, | sed -e 's/T.*//') +1 day" +"%Y-%m-%dT00:00:00")"

gnuplot -c quality.gnuplot "$datafile" "$startdate" "$enddate" > "$outfile"
rm -f "$datafile"
